name: 'Paola & Pascal'
favicon: null
layout_spectrum: 0.9383769438136369
typography_spectrum: 0.09196786675602198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130f10'
    - '#d0d4f9'
    - '#6e5034'
    - '#ff9d62'
    - '#9c0a6f'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
